name: mi
description: A new Flutter project.
publish_to:
version: 1.0.0+1
environment:
  sdk: '>=3.0.6 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - images/bg_1.png
  fonts:
  - family: pacifico
    fonts:
    - asset: fonts/Pacifico-Regular.ttf

  - family: Source Code Pro
    fonts:
      - asset: fonts/SourceCodePro-Regular.ttf

